import Navbar from "@/components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { dark } from "@clerk/themes";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: [dark],
      }}
    >
      <html data-theme="dracula" lang="en">
        <body className={inter.className}>
          <div className=" mx-auto">
            <Navbar />
          </div>
          <div className="mt-8 max-w-3xl mx-auto">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
